{include file="addons/cp_open_graph/views/components/fb_preview_button.tpl" preview_url=$og_data.preview_url|default:$og_auto_data.preview_url}

{$obj_type = $og_data.object_type|default:$og_auto_data.object_type}
{$obj_id = $og_data.object_id|default:$og_auto_data.object_id}

{$og_multi_images=""|fn_cp_og_get_multi_images_scheme}

<input type="hidden" name="{$input_prefix}[cp_og_data][object_id]" value="{$obj_id}">
<input type="hidden" name="{$input_prefix}[cp_og_data][object_type]" value="{$obj_type}">

{if $only_manual}
    {$is_auto = false}
{elseif $og_type == $smarty.const.CP_OG_DATA_AUTO}
    {$is_auto = true}   
{/if}

<div id="cp_open_graph_{$obj_type}_hook" class="in collapse">
    {if !$only_manual}
    <div class="control-group cp-og-type-change">
        <label class="control-label cm-required">{__("cp_og.info_type")}:</label>
        <div class="controls">
            <label class="radio inline" for="cp_og_type_auto"><input type="radio" name="{$input_prefix}[cp_og_data_type]" id="cp_og_type_auto" checked="checked" {if $is_auto}checked="checked"{/if} value="{$smarty.const.CP_OG_DATA_AUTO}"/>{__("cp_od.autogenerated")}</label>
            <label class="radio inline" for="cp_og_type_manual"><input type="radio" name="{$input_prefix}[cp_og_data_type]" id="cp_og_type_manual" {if $og_type == $smarty.const.CP_OG_DATA_MANUAL}checked="checked"{/if} value="{$smarty.const.CP_OG_DATA_MANUAL}" />{__("cp_og.manual")}</label>
        </div>
    </div>
    {/if}

    <div id="cp_og_data_manual" class="{if $is_auto} hidden{/if}">
        <div class="control-group">
            <label for="elm_cp_og_title" class="control-label cm-required">{__("title")}:</label>
            <div class="controls">
                <input class="input-large" type="text" name="{$input_prefix}[cp_og_data][cp_og_title]" id="elm_cp_og_title" size="55" value="{$og_data.title}" {if $is_auto}disabled="disabled"{/if} />
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="elm_cp_og_desctiption">{__("cp_og.description")}:</label>
            <div class="controls">
                <textarea id="elm_cp_og_desctiption" name="{$input_prefix}[cp_og_data][cp_og_description]" cols="55" rows="5" class="input-large" {if $is_auto}disabled="disabled"{/if}>{$og_data.description}</textarea>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">{__("image")}{include file="common/tooltip.tpl" tooltip=__("cp_og.image_alt_description")}:</label>
            <div class="controls">
                {include file="common/attach_images.tpl" image_name="`$smarty.const.CP_OG_IMG_PAIR_PREFIX`image_`$obj_type`" image_object_type="`$smarty.const.CP_OG_IMG_PAIR_PREFIX``$obj_type`" image_pair=$og_data.image_pair image_object_id=$obj_id no_thumbnail=true hide_alt=false}
            </div>
        </div>
        {if $og_multi_images}
            {foreach from=$og_multi_images item="og_multi" key="og_img_key"}
                <div class="control-group">
                    <label class="control-label">{$og_multi.label}{include file="common/tooltip.tpl" tooltip=$og_multi.tooltip}:</label>
                    <div class="controls">
                        {include file="common/attach_images.tpl" image_name="`$og_multi.prefix`image_`$obj_type`" image_object_type="`$og_multi.prefix``$obj_type`" image_pair=$og_data.og_images.$og_img_key image_object_id="`$obj_id`_`$og_img_key`" no_thumbnail=true hide_alt=false}
                    </div>
                </div>
            {/foreach}
        {/if}
    </div>

    {if !$only_manual}
        <div id="cp_og_data_auto" class="{if !$is_auto} hidden{/if}">
            <div class="control-group">
                <label class="control-label">{__("title")}:</label>
                <div class="controls">
                    <span>{$og_auto_data.title}</span>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label">{__("cp_og.description")}:</label>
                <div class="controls">
                    <span>{$og_auto_data.description}</span>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label">{__("image")}:</label>
                <div class="controls">
                    <div class="cp_og_auto_img">
                        {assign var="cp_og_img" value=$og_auto_data.image}
                        {include file="common/image.tpl" image=$cp_og_img image_width=85}
                    </div>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label">{__("cp_og.image_alt")}{include file="common/tooltip.tpl" tooltip=__("cp_og.image_alt_description")}:</label>
                <div class="controls">
                    <span>{$cp_og_img.alt}</span>
                </div>
            </div>
        </div>
    {/if}
</div>
